### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by redtide** [sjaehn/lv2tutorial#11]
Maybe issues is not the best place for a list of (possible) additions, maybe could it be a shared [project](https://github.com/sjaehn/lv2tutorial/projects?query=is%3Aopen) or convert this to a discussion?

- It is not necessary (IMO) to make a video for each of the following.
- These are just ideas that I can also help to realize, to be discussed which implement or not, depending on the project scope.

- [ ] Make the repo a bit cleaner by subdividing things in folders, so adding some more referenced docs outside readme:
```
|_examples
| |_ myAmp...
|_docs
| |_ License-options.md
| |_ Build-systems-cmake-makefile-meson.md
| |_ UI-adding-resources.md
| |_ ...
|_README.md
|_ ...
```
- [ ] License options: liberal and viral to choose for plugins
- [ ] 1/3 Brief introduction to build systems to choose
- [ ] 2/3 Build script examples
- [ ] 3/3 Add dependencies and minimal script references/examples (e.g. [XPutty](https://github.com/archlinux/aur/blob/xputty-git/PKGBUILD#L36-L39))
- [ ] UI plugins: add resources
- [ ] Advanced: Git submodules / Meson subprojects
- [ ] Advanced: Multiplatform compatibility
- [ ] Advanced: 1/2 Working GH Actions CI script for this repo also as example
- [ ] Advanced: 2/2 Brief introduction to CI (GH Actions only should suffice)

**Comment by sjaehn** [comment]
Lots of ideas. Thanks. I moved the first two to new issues. Easier to handle. The others could be object of a new tutorial series. But I'm not sure if I'm the right one for this.

**Comment by redtide** [comment]
> But I'm not sure if I'm the right one for this.

Me or someone else could contribute something, then you can give it a look and decide if will be something that you can keep for maintenance in the repo. In the worst case can go in a separated, community maintained wiki. IIRC you can enable a wiki for the project in settings and set it writable by anyone/contributors, for example.

**Comment by redtide** [comment]
I'm working on the splitted documents, to show also them in a website generated from this repo.
I see now in README file a lots of inline links (which are not surrounded by `<` and `>` like in standard markdown, so not usable in other parsers) instead of references.
Maybe some are OK to keep inline, so just adjust them, from:

```markdown
See video: https://the-possibly-loooooong-ugly-url-video-link
```

to

```markdown
See video: <https://the-possibly-loooooong-ugly-url-video-link>
```

if not

```markdown
[See video on YT](the-possibly-loooooong-ugly-url-video-link)
```
or, eventually some others, making them readable from a text editor:
```markdown
[See video on YT][video001]

some (much) more content here...


and at the end of the README:
[video001]: the-possibly-loooooong-ugly-url-video-link
```

ideas? Will follow a PR
